name: ci

on: push

env:
  APP_NAME: sonarqube
  APP_NAMESPACE: kube-system
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  AWS_DEFAULT_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: prepare EKS
        env:
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws eks update-kubeconfig --name senacor-cicd-deployment \
          --region eu-west-2 \
          --role-arn arn:aws:iam::604370441254:role/StateOfTheArtCICD
      - name: deploy sonar
        run: |
          ls -la
