name: ci

on: push

env:
  APP_NAME: sonarqube
  APP_NAMESPACE: kube-system

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy sonar
        run: |
          helm upgrade sonarqube ./Deployment/charts/sonarqube/ --install --wait --atomic --namespace= kube-system --set=app.name= sonarqube --values=./Deployment/charts/sonarqube/values.yaml
