name: ci

on: push

env:
  APP_NAME: sonarqube
  APP_NAMESPACE: kube-system

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy sonar
        run: |
          helm upgrade --install -f ./Deployment/charts/sonarqube/values.yaml -n kube-system sonarqube ./Deployment/charts/sonarqube/
